name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build step
        uses: denoland/deployctl@v1
        with:
          project: "deep-pike-64"
          entrypoint: "lib/build.ts"
          root: "." 

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "deep-pike-64"
          entrypoint: "lib/start.ts"
          root: "." 
